### ISSUE TITLE
Using two tasks is wrong. Use one Task instead.

### ISSUE THREAD

**Issue by tonjy** [gitpod-samples/template-python-django#11]
### Bug description

The gitpod.yml tasks specification uses two tasks instead of one.
Therefore the init and the command are not synced.
This can lead to the situation where the command is started to soon, and you get strage erroes, because the venv is missing, or the dependencies are not installed correctly.

### Steps to reproduce

Add some longer commands to the 'init' step, e.g. sleep 30.

### Expected behavior

There is only 1 task instead.

**Comment by antonjahn** [comment]
Fixed with https://github.com/gitpod-samples/template-python-django/commit/443083d83bb72d7fa7d833164c06de97473b9088
